// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1xdjTrI0dQNVchHAFCBRBj2NHJxToq4',
    appId: '1:292426184503:web:a92de35e25b8c16c8fccb2',
    messagingSenderId: '292426184503',
    projectId: 'deliverly-4811e',
    authDomain: 'deliverly-4811e.firebaseapp.com',
    storageBucket: 'deliverly-4811e.firebasestorage.app',
    measurementId: 'G-TQEF5BC7W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvuwVDKQKx-fHJ7Lu4_IyV7bYy2-l2hw',
    appId: '1:292426184503:android:a02e474918df5fcc8fccb2',
    messagingSenderId: '292426184503',
    projectId: 'deliverly-4811e',
    storageBucket: 'deliverly-4811e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlhOaPor6qfjs48Yjd9PjlAWsbJQUxJk',
    appId: '1:292426184503:ios:36e7ba03166722118fccb2',
    messagingSenderId: '292426184503',
    projectId: 'deliverly-4811e',
    storageBucket: 'deliverly-4811e.firebasestorage.app',
    iosBundleId: 'com.ivan.delivery',
  );

}