// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLFz22RPTDxPDxUx0w0cF7PIUInGjcOI',
    appId: '1:413010641256:web:6ec5ba02eaf40ce13316dd',
    messagingSenderId: '413010641256',
    projectId: 'deliverly-2f903',
    authDomain: 'deliverly-2f903.firebaseapp.com',
    storageBucket: 'deliverly-2f903.firebasestorage.app',
    measurementId: 'G-5MFWPDKYD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsqcKrPQUGqvU_EScI2xE6K-itSPshnng',
    appId: '1:413010641256:android:1be6c858c00d72a33316dd',
    messagingSenderId: '413010641256',
    projectId: 'deliverly-2f903',
    storageBucket: 'deliverly-2f903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXnVE3eVWKWzZ8FF-lnUwROv6f9fXkRO8',
    appId: '1:413010641256:ios:134234442cfd3b0d3316dd',
    messagingSenderId: '413010641256',
    projectId: 'deliverly-2f903',
    storageBucket: 'deliverly-2f903.firebasestorage.app',
    iosBundleId: 'com.ivan.delivery',
  );

}