// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFwKicGYHoCobn8B8lzsfb9AmENOOEKsA',
    appId: '1:10243427761:web:599ae7bc9edf3695700190',
    messagingSenderId: '10243427761',
    projectId: 'deliverly-launch',
    authDomain: 'deliverly-launch.firebaseapp.com',
    storageBucket: 'deliverly-launch.firebasestorage.app',
    measurementId: 'G-Y669Y9JBWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6FqxCYm46Kg4yKFBKuARtAHFdySOajM',
    appId: '1:10243427761:android:54537c71c32ca8b9700190',
    messagingSenderId: '10243427761',
    projectId: 'deliverly-launch',
    storageBucket: 'deliverly-launch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPztriwQxawrBedJycTZCOqVPRyrJ6yPI',
    appId: '1:10243427761:ios:025de6237df7f205700190',
    messagingSenderId: '10243427761',
    projectId: 'deliverly-launch',
    storageBucket: 'deliverly-launch.firebasestorage.app',
    iosBundleId: 'com.ivan.delivery',
  );

}